### ISSUE TITLE
Any plans for Rollbar reporter?

### ISSUE THREAD

**Issue by edbizarro** [esbenp/heimdal#10]

**Comment by esbenp** [comment]
Sure, it would be fairly easy to add. Would you dare to take a crack at a PR? :-) You can just copy the sentry or bugsnag reporter and fit it to Rollbar

**Comment by edbizarro** [comment]
yeah, I'll give it a shot :D

**Comment by edbizarro** [comment]
done! #11

**Comment by esbenp** [comment]
Booom! #awesomesauce I will take a look :-)

**Comment by esbenp** [comment]
I just pushed #12 which changes the way reporters are instantiated. Can you add the rollbar reporter to the service provider as well?

**Comment by edbizarro** [comment]
sure!

**Comment by esbenp** [comment]
Merged and released in 1.4.0! Thanks for your contribution @edbizarro this is awesome :-)
