### ISSUE TITLE
Laravel 6.0

### ISSUE THREAD

**Issue by JexPY** [esbenp/heimdal#29]
We need 6.0 support

**Comment by rdehnhardt** [comment]
I think this package is abandoned!

**Comment by JexPY** [comment]
Yea me too, so I decided to remove this package from my API and rebuild the exceptions logic by myself... This -> [https://culttt.com/2015/08/10/dealing-with-exceptions-in-a-laravel-api-application/](https://culttt.com/2015/08/10/dealing-with-exceptions-in-a-laravel-api-application/) helped a lot.

Best regards

**Comment by esbenp** [comment]
Check `2.0.0`
