### ISSUE TITLE
Conflict with Laravel Passport

### ISSUE THREAD

**Issue by josvar** [esbenp/heimdal#7]
The report method of the `Optimus\Heimdal\ExceptionHandler` class returns an array, when it should not. 

This is the contract that the handler method should follow: 
`Illuminate\Contracts\Debug\ExceptionHandler;`

```
    /**
     * Report or log an exception.
     *
     * @param  \Exception  $e
     * @return void
     */
    public function report(Exception $e);
```

Thanks.

**Comment by esbenp** [comment]
Fixed in `1.2.2`
